#!/usr/bin/env bash
set -euo pipefail

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-4}" python -u stereo_lidar.py \
  --checkpoint_dir outputs/luna_finetune_bs8_lr1e7_continue200_exclude2 \
  --train_datasets luna \
  --test_datasets luna \
  --luna_root /mnt/data/jianglai/artifacts/SDG-Depth-main/batch_organized \
  --luna_exclude_sequences 2025-06-26-22-59-05 2025-06-26-23-01-34 \
  --resume_ckpt outputs/luna_finetune_bs8_lr1e6_ep50_exclude2/ckpt_best.pth \
  --strict_resume 0 \
  --max_disp 192 \
  --image_size 256 512 \
  --occlusion_aug_prob 0.5 \
  --guided_flag 1 \
  --cfnet_confidence_value 0.4 \
  --gsm_validhint conf_04 \
  --gaussian_h 2 \
  --gaussian_w 8 \
  --refine_spn_r 4 \
  --refine_spn_resolution 4 \
  --refine_spn_conf_pixel sparse_valid_all \
  --refine_spn_offset_flag 1 \
  --disp_to_depth_convert_flag 1 \
  --disp_to_depth_convert_resolution 2 \
  --disp_to_depth_convert_gate 0.1 \
  --disp_to_depth_convert_disp_range 0.2 \
  --disp_to_depth_convert_depth_range 0.6 \
  --pred_hint_weight 0.5 \
  --disp_to_depth_convert_loss_weight1 0.7 \
  --disp_to_depth_convert_loss_weight2 0.7 \
  --batch_size 8 \
  --num_workers 8 \
  --num_steps 13600 \
  --num_epoch 200 \
  --lr 1e-7 \
  --lr_scheduler_type MultiStepLR \
  --milestones 150 \
  --lr_gamma 0.1 \
  --val_epoch 1 \
  --mixed_precision